version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PYTHON_SERVICE_URL=http://python-service:8000
    depends_on:
      - python-service

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./python-service/app:/app/app
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload 