name: BankRewards Daily Collection

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'production'

env:
  FIRESTORE_EMULATOR_HOST: localhost:8080
  FIREBASE_STORAGE_EMULATOR_HOST: localhost:9199
  NEXT_PUBLIC_USE_FIREBASE_EMULATORS: 'false'
  GOOGLE_APPLICATION_CREDENTIALS: ./firebase-service-account.json
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
  # BankRewards specific configuration
  BANKREWARDS_MAX_CONCURRENCY: '2'
  BANKREWARDS_MAX_REQUESTS_PER_MINUTE: '20'
  BANKREWARDS_MAX_RETRIES: '3'
  BANKREWARDS_TIMEOUT_SECS: '30'
  BANKREWARDS_STORAGE_DIR: '/tmp/bankrewards'
  BANKREWARDS_LOG_LEVEL: 'info'

jobs:
  collect-and-store:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set a timeout to prevent hung jobs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1  # Only install chromium

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Set up Firebase credentials
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}' | base64 -d > firebase-service-account.json
          echo "Firebase credentials configured"

      - name: Run collection script
        run: |
          mkdir -p /tmp/bankrewards
          node dist/src/lib/scrapers/bankrewards/collector.js
        env:
          NODE_ENV: production

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload to Firebase Storage
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          FILENAME="bankrewards_${TIMESTAMP}.json"
          mv /tmp/bankrewards/data.json "./${FILENAME}"
          
          # Upload to Firebase Storage with the timestamped filename
          firebase storage:upload "./${FILENAME}" \
            --project ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} \
            --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}" \
            --public \
            "bankrewards/${FILENAME}"

      - name: Cleanup
        if: always()
        run: |
          rm -f firebase-service-account.json
          rm -rf /tmp/bankrewards