name: Create PR from develop to master

on:
  push:
    branches:
      - develop
  workflow_dispatch:  # Allows manual trigger

permissions:
  pull-requests: write
  contents: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if there's already an open PR
          if ! gh pr list --head develop --base master --state open | grep -q .; then
            # Create PR if none exists
            gh pr create --base master --head develop \
              --title "chore: merge develop into master" \
              --body "Automated PR to merge develop into master"
          fi