name: Create PR from develop to master

on:
  push:
    branches:
      - develop
  workflow_dispatch:  # Allows manual trigger

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "master"
          pr_title: "chore: merge develop into master"
          pr_body: "Automated PR to merge develop into master"
          github_token: ${{ secrets.GITHUB_TOKEN }}